config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :projects

  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence: true
  attribute :name, default: "Untitled Project"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects
  def index
    @projects = Project.order('created_at desc')
  end

  # GET /projects/1 or /projects/1.json
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    saved = @project.save
    return render :new, status: :unprocessable_entity unless saved

    redirect_to projects_url, notice: "Project was successfully created."
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      return redirect_to project_url(@project), notice: "Project was successfully updated."
    end

    render :edit, status: :unprocessable_entity
  end

  # DELETE /projects/1
  def destroy
    @project.destroy!

    redirect_to projects_url, notice: "Project was successfully deleted."
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_model_errors(model)
    render partial: "shared/model_errors", locals: { model: model }
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def table_header(title, first: false)
    render partial: "projects/table_header", locals: {title: title, table_header_class: table_header_class(first) }
  end

  private

  def table_header_class(first)
    return "py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-0" if first

    "px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>DragonrubySceneEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-full">
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<div id="myModal" class="fixed top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 p-8 bg-white border
                       border-gray-300 shadow-md z-50"
                  data-controller="modal">
  <h2 class="text-2xl font-bold mb-4">Create Project</h2>
  <%= form_with(model: project, class: "flex flex-col", data: { modal_target: "form" }) do |form| %>
    <% if project.errors.any? %>
      <%= display_model_errors(project) %>
    <% end %>
    <div class="pb-7">
      <%= form.label :name, class: "block text-sm font-medium leading-6 text-gray-900" %>
      <div class="relative mt-2">
        <%= form.text_field :name, class: "peer block w-full border-0 bg-gray-50 py-1.5 text-gray-900 focus:ring-0
                                           sm:text-sm sm:leading-6" %>
        <div class="absolute inset-x-0 bottom-0 border-t border-gray-300 peer-focus:border-t-2 peer-focus:border-indigo-600" aria-hidden="true"></div>
      </div>
    </div>
    <div class="mt-5 sm:mt-6 sm:grid sm:grid-flow-row-dense sm:grid-cols-2 sm:gap-3">
      <%= form.submit class: "inline-flex w-full justify-center rounded-md
                                 bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm
                                 hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2
                                   focus-visible:outline-offset-2 focus-visible:outline-indigo-600 sm:col-start-2",
                      data: { turbo_frame: "projects" } %>
      <button type="button" class="mt-3 inline-flex w-full justify-center rounded-md bg-white px-3 py-2
                                   text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset
                                   ring-gray-300 hover:bg-gray-50 sm:col-start-1 sm:mt-0"
                                   data-action="modal#cancel">
        Cancel
      </button>

    </div>
  <% end %>
</div>

app/views/projects/_project.html.erb
  <tr id="<%= dom_id project %>" class="hover:bg-gray-100" data-controller="table-row"
      data-action="click->table-row#click" data-table-row-href-value=<%= edit_project_path(project) %>>
    <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-0">
      <%= project.name %>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
      <%= project.updated_at %>
    </td>
    <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
      Member
    </td>
    <td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm sm:pr-0">
      <%= button_to project_path(project.id), class: "font-bold text-red-600 hover:text-red-900",
                  method: :delete, data: { action: "table-row#innerButtonClick",
                                           turbo_frame: "projects" } do %>
        Delete
        <span class="sr-only">, <%= project.name %></span>
      <% end %>
    </td>
  </tr>

app/views/projects/_table_header.html.erb
<%= tag.th scope: "col", class: table_header_class do %>
  <a href="#" class="group inline-flex">
    <%= title %>
    <!-- Active: "bg-gray-200 text-gray-900 group-hover:bg-gray-300", Not Active: "invisible text-gray-400 group-hover:visible group-focus:visible" -->
    <span class="invisible ml-2 flex-none rounded text-gray-400 group-hover:visible group-focus:visible">
      <svg class="invisible ml-2 h-5 w-5 flex-none rounded text-gray-400 group-hover:visible group-focus:visible" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
      </svg>
    </span>
  </a>
<% end%>

app/views/projects/create.turbo_stream.erb
<%= turbo_stream.prepend 'projects_tbody', render(@project) %>

app/views/projects/delete.turbo_stream.erb
<%= turbo_stream.remove @project %>

app/views/projects/edit.html.erb
<div class="bg-gray-700 border-b-2 border-gray-500 text-white xl:px-2 py-2">
    <%= link_to "Back to projects", projects_path, class: "text-xl underline" %>
</div>

<div id="app" data-controller="vue" data-vue-target="root" class="h-full flex flex-col">

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag "modal" %>

<div class="px-4 sm:px-6 lg:px-8">
  <div class="border-gray-200 bg-white py-5">
    <div class="-ml-4 -mt-2 flex flex-wrap items-center justify-between sm:flex-nowrap">
      <div class="ml-4 mt-2">
        <h3 class="text-base font-semibold leading-6 text-gray-900">Projects</h3>
      </div>
      <div class="ml-4 mt-2 flex-shrink-0">
        <%= button_to "Create new project", new_project_path, type: "button", method: :get,
                      class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm
                              font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline
                              focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600",
                      data: { turbo_frame: "modal" } %>
      </div>
    </div>
  </div>

  <div class="mt-4 flow-root">
      <div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8">
          <%= turbo_frame_tag "projects" do %>
            <table class="min-w-full divide-y divide-gray-300">
              <thead>
                <tr>
                  <%= table_header("Name", first: true) %>
                  <%= table_header("Updated") %>
                  <%= table_header("Contributors") %>
                  <th scope="col" class="relative py-3.5 pl-3 pr-0">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
                <tbody id="projects_tbody" class="divide-y divide-gray-200 bg-white">
                    <% @projects.each do |project |%>
                      <%= render project %>
                    <% end %>
                </tbody>
            </table>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<%= turbo_frame_tag "modal", data: {controller: "modal"} do %>
  <%= render "form", project: @project %>
  <div id="overlay" class="fixed top-0 left-0 w-full h-full bg-black bg-opacity-75 z-40"></div>
<% end%>

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @project %>

<div>
  <%= link_to "Edit this project", edit_project_path(@project) %> |
  <%= link_to "Back to projects", projects_path %>

  <%= button_to "Destroy this project", @project, method: :delete %>
</div>

app/views/shared/_model_errors.html.erb
<div style="color: red">
  <h2><%= pluralize(model.errors.count, "error") %> prohibited this project from being saved:</h2>

  <ul>
    <% model.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>